// Curated static seed; no runtime API/search dependency.
// Wikipedia facts and Commons images verified with scripts/import-wikimedia.mjs.
// Descriptions/whyVisit are original editorial summaries, not copied extracts.
// durationMinutes is a planning estimate, never an opening-hours claim.
// outdoor means mainly open-air; mixed indoor/outdoor sites may be marked true.
// Coordinates are attraction locations, not routing or accessibility guarantees.
// Display imageCredit + imageLicense and link imageSource / imageLicenseUrl.

export const places = [
  {
    "id": "drachenburg",
    "name": "Schloss Drachenburg",
    "city": "Königswinter",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.6686729,
    "lng": 7.2063442,
    "category": "architecture",
    "outdoor": true,
    "description": "A turreted 1880s villa dressed as a medieval palace, high above the Rhine on the Drachenfels hillside.",
    "whyVisit": "For storybook towers, ornate rooms and Rhine-valley panoramas in one short trip from Bonn.",
    "durationMinutes": 120,
    "wikipedia": "https://en.wikipedia.org/wiki/Schloss_Drachenburg",
    "website": "https://www.schloss-drachenburg.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Aerial_image_of_Schloss_Drachenburg_%28view_from_the_northeast%29.jpg/960px-Aerial_image_of_Schloss_Drachenburg_%28view_from_the_northeast%29.jpg",
    "imageFile": "Aerial image of Schloss Drachenburg (view from the northeast).jpg",
    "imageCredit": "Carsten Steger",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_Schloss_Drachenburg_(view_from_the_northeast).jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Aerial_image_of_Schloss_Drachenburg_%28view_from_the_northeast%29.jpg",
    "wikipediaPageId": 26947068,
    "wikipediaRevisionId": 1377215962,
    "wikidataId": "Q315089",
    "wikidata": "https://www.wikidata.org/wiki/Q315089",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Schloss_Drachenburg",
      "https://www.wikidata.org/wiki/Q315089",
      "https://www.schloss-drachenburg.de/"
    ]
  },
  {
    "id": "drachenfels",
    "name": "Drachenfels",
    "city": "Königswinter",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.66527778,
    "lng": 7.20972222,
    "category": "nature",
    "outdoor": true,
    "description": "A volcanic hill crowned by a ruined castle, with sweeping views over a dramatic bend in the Rhine.",
    "whyVisit": "Walk through the Siebengebirge or pair the summit with the historic rack railway.",
    "durationMinutes": 120,
    "wikipedia": "https://en.wikipedia.org/wiki/Drachenfels_(Siebengebirge)",
    "website": "https://www.drachenfelsbahn.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/20130816_Drachenfels.jpg/960px-20130816_Drachenfels.jpg",
    "imageFile": "20130816 Drachenfels.jpg",
    "imageCredit": "Dmitry Tonkonog and Ksenia Fedosova",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:20130816_Drachenfels.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/d/de/20130816_Drachenfels.jpg",
    "wikipediaPageId": 2677390,
    "wikipediaRevisionId": 1241317557,
    "wikidataId": "Q703922",
    "wikidata": "https://www.wikidata.org/wiki/Q703922",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Drachenfels_(Siebengebirge)",
      "https://www.wikidata.org/wiki/Q703922",
      "https://www.drachenfelsbahn.de/"
    ]
  },
  {
    "id": "bruder-klaus-chapel",
    "name": "Bruder Klaus Field Chapel",
    "city": "Mechernich",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.592414,
    "lng": 6.727332,
    "category": "architecture",
    "outdoor": false,
    "description": "Peter Zumthor’s stark concrete chapel stands alone in Eifel farmland, hiding a dark, intimate interior.",
    "whyVisit": "The contrast between open fields and the small, sculptural sanctuary is the whole experience.",
    "durationMinutes": 60,
    "wikipedia": "https://de.wikipedia.org/wiki/Bruder-Klaus-Feldkapelle",
    "website": "https://www.feldkapelle.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Bruder-Klaus-Feldkapelle_%28Wachendorf%29_003x.jpg/960px-Bruder-Klaus-Feldkapelle_%28Wachendorf%29_003x.jpg",
    "imageFile": "Bruder-Klaus-Feldkapelle (Wachendorf) 003x.jpg",
    "imageCredit": "Wolkenkratzer",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Bruder-Klaus-Feldkapelle_(Wachendorf)_003x.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Bruder-Klaus-Feldkapelle_%28Wachendorf%29_003x.jpg",
    "wikipediaPageId": 5563462,
    "wikipediaRevisionId": 270537662,
    "wikidataId": "Q992149",
    "wikidata": "https://www.wikidata.org/wiki/Q992149",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Bruder-Klaus-Feldkapelle",
      "https://www.wikidata.org/wiki/Q992149",
      "https://www.feldkapelle.de/"
    ]
  },
  {
    "id": "government-bunker",
    "name": "Government Bunker",
    "city": "Bad Neuenahr-Ahrweiler",
    "region": "Rhineland-Palatinate",
    "country": "Germany",
    "lat": 50.54111111,
    "lng": 7.08111111,
    "category": "museums",
    "outdoor": false,
    "description": "A preserved fragment of West Germany’s secret Cold War government shelter, built inside former railway tunnels.",
    "whyVisit": "Step into the emergency world designed for officials from nearby Bonn; visit the documented museum, not abandoned tunnels.",
    "durationMinutes": 90,
    "wikipedia": "https://de.wikipedia.org/wiki/Regierungsbunker_(Deutschland)",
    "website": "https://www.regbu.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/98/Regierungsbunker_Doku_Eingang.jpg",
    "imageFile": "Regierungsbunker Doku Eingang.jpg",
    "imageCredit": "Axel Hindemith",
    "imageLicense": "Public domain",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Regierungsbunker_Doku_Eingang.jpg",
    "imageLicenseUrl": "",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/9/98/Regierungsbunker_Doku_Eingang.jpg",
    "wikipediaPageId": 111715,
    "wikipediaRevisionId": 267872712,
    "wikidataId": "Q264850",
    "wikidata": "https://www.wikidata.org/wiki/Q264850",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Regierungsbunker_(Deutschland)",
      "https://www.wikidata.org/wiki/Q264850",
      "https://www.regbu.de/"
    ]
  },
  {
    "id": "arp-museum",
    "name": "Arp Museum Bahnhof Rolandseck",
    "city": "Remagen",
    "region": "Rhineland-Palatinate",
    "country": "Germany",
    "lat": 50.63138889,
    "lng": 7.20694444,
    "category": "museums",
    "outdoor": false,
    "description": "A 19th-century railway station meets Richard Meier’s bright white hillside museum, with art by Hans Arp and Sophie Taeuber-Arp.",
    "whyVisit": "A memorable collision of railway heritage, modern architecture and sculpture beside the Rhine.",
    "durationMinutes": 120,
    "wikipedia": "https://de.wikipedia.org/wiki/Arp_Museum_Bahnhof_Rolandseck",
    "website": "https://arpmuseum.org/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/f8/ARPMUS.jpg",
    "imageFile": "ARPMUS.jpg",
    "imageCredit": "Hans Weingartz",
    "imageLicense": "CC BY-SA 2.0 de",
    "imageSource": "https://commons.wikimedia.org/wiki/File:ARPMUS.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/de/deed.en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/f/f8/ARPMUS.jpg",
    "wikipediaPageId": 2944948,
    "wikipediaRevisionId": 259713882,
    "wikidataId": "Q698582",
    "wikidata": "https://www.wikidata.org/wiki/Q698582",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Arp_Museum_Bahnhof_Rolandseck",
      "https://www.wikidata.org/wiki/Q698582",
      "https://arpmuseum.org/"
    ]
  },
  {
    "id": "bonn-botanical-gardens",
    "name": "Bonn Botanical Gardens",
    "city": "Bonn",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.72472222,
    "lng": 7.09166667,
    "category": "nature",
    "outdoor": true,
    "description": "University plant collections and glasshouses surround Poppelsdorf Palace, bringing exotic botany into the middle of Bonn.",
    "whyVisit": "Trade the obvious city sights for a living research collection, palace gardens and tropical glasshouse atmosphere.",
    "durationMinutes": 90,
    "wikipedia": "https://de.wikipedia.org/wiki/Botanischer_Garten_Bonn",
    "website": "https://www.botgart.uni-bonn.de/de",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/84/Botgartenbonn19.jpg",
    "imageFile": "Botgartenbonn19.jpg",
    "imageCredit": "Matthias Habel, Bonn",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Botgartenbonn19.jpg",
    "imageLicenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/8/84/Botgartenbonn19.jpg",
    "wikipediaPageId": 1283298,
    "wikipediaRevisionId": 270401499,
    "wikidataId": "Q322634",
    "wikidata": "https://www.wikidata.org/wiki/Q322634",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Botanischer_Garten_Bonn",
      "https://www.wikidata.org/wiki/Q322634",
      "https://www.botgart.uni-bonn.de/de"
    ]
  },
  {
    "id": "augustusburg-palace",
    "name": "Augustusburg Palace",
    "city": "Brühl",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.8275,
    "lng": 6.90805556,
    "category": "architecture",
    "outdoor": true,
    "description": "An exuberant 18th-century Rococo palace and formal gardens, part of Brühl’s UNESCO-listed palace ensemble.",
    "whyVisit": "The theatrical staircase and landscaped grounds make a grand, easy detour between Bonn and Cologne.",
    "durationMinutes": 120,
    "wikipedia": "https://en.wikipedia.org/wiki/Augustusburg_and_Falkenlust_Palaces,_Br%C3%BChl",
    "website": "https://www.schlossbruehl.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Br%C3%BChl_Schloss_Augustusburg_asv2024-05_img06.jpg/960px-Br%C3%BChl_Schloss_Augustusburg_asv2024-05_img06.jpg",
    "imageFile": "Brühl Schloss Augustusburg asv2024-05 img06.jpg",
    "imageCredit": "A.Savin",
    "imageLicense": "FAL",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Br%C3%BChl_Schloss_Augustusburg_asv2024-05_img06.jpg",
    "imageLicenseUrl": "http://artlibre.org/licence/lal/en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Br%C3%BChl_Schloss_Augustusburg_asv2024-05_img06.jpg",
    "wikipediaPageId": 872854,
    "wikipediaRevisionId": 1366152355,
    "wikidataId": "Q156292",
    "wikidata": "https://www.wikidata.org/wiki/Q156292",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Augustusburg_and_Falkenlust_Palaces,_Br%C3%BChl",
      "https://www.wikidata.org/wiki/Q156292",
      "https://www.schlossbruehl.de/"
    ]
  },
  {
    "id": "effelsberg-telescope",
    "name": "Effelsberg Radio Telescope",
    "city": "Bad Münstereifel",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.5247,
    "lng": 6.8828,
    "category": "industrial",
    "outdoor": true,
    "description": "A steerable, 100-metre radio telescope rises out of a wooded Eifel valley like a giant listening dish.",
    "whyVisit": "See astronomical engineering at landscape scale from the visitor viewpoints and surrounding trails.",
    "durationMinutes": 90,
    "wikipedia": "https://en.wikipedia.org/wiki/Effelsberg_100-metre_Radio_Telescope",
    "website": "https://www.mpifr-bonn.mpg.de/effelsberg",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Radioteleskop_Effelsberg-0197.jpg/960px-Radioteleskop_Effelsberg-0197.jpg",
    "imageFile": "Radioteleskop Effelsberg-0197.jpg",
    "imageCredit": "© Raimond Spekking / CC BY-SA 4.0 (via Wikimedia Commons)",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Radioteleskop_Effelsberg-0197.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/9/94/Radioteleskop_Effelsberg-0197.jpg",
    "wikipediaPageId": 1066000,
    "wikipediaRevisionId": 1333820202,
    "wikidataId": "Q705139",
    "wikidata": "https://www.wikidata.org/wiki/Q705139",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Effelsberg_100-metre_Radio_Telescope",
      "https://www.wikidata.org/wiki/Q705139",
      "https://www.mpifr-bonn.mpg.de/effelsberg"
    ]
  },
  {
    "id": "andernach-geyser",
    "name": "Andernach Geyser",
    "city": "Andernach",
    "region": "Rhineland-Palatinate",
    "country": "Germany",
    "lat": 50.448333,
    "lng": 7.375278,
    "category": "nature",
    "outdoor": true,
    "description": "A carbon-dioxide-driven cold-water geyser shoots a jet of water from the Namedyer Werth peninsula on the Rhine.",
    "whyVisit": "An unusual natural spectacle paired with the official visitor experience; the geyser is not an unrestricted walk-up site.",
    "durationMinutes": 180,
    "wikipedia": "https://en.wikipedia.org/wiki/Andernach_Geyser",
    "website": "https://www.geysir-andernach.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Geysir_Andernach_2009.JPG/960px-Geysir_Andernach_2009.JPG",
    "imageFile": "Geysir Andernach 2009.JPG",
    "imageCredit": "Holger Weinandt",
    "imageLicense": "CC BY-SA 3.0 de",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Geysir_Andernach_2009.JPG",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Geysir_Andernach_2009.JPG",
    "wikipediaPageId": 49952841,
    "wikipediaRevisionId": 1365273508,
    "wikidataId": "Q15111605",
    "wikidata": "https://www.wikidata.org/wiki/Q15111605",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Andernach_Geyser",
      "https://www.wikidata.org/wiki/Q15111605",
      "https://www.geysir-andernach.de/"
    ]
  },
  {
    "id": "kolumba",
    "name": "Kolumba",
    "city": "Cologne",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 50.938889,
    "lng": 6.954722,
    "category": "museums",
    "outdoor": false,
    "description": "A quiet art museum rises around the ruins of St. Kolumba church, incorporating a postwar chapel into its architecture.",
    "whyVisit": "Look for the layered meeting of archaeology, sacred art and Peter Zumthor’s carefully controlled light.",
    "durationMinutes": 90,
    "wikipedia": "https://en.wikipedia.org/wiki/Kolumba",
    "website": "https://www.kolumba.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Kolumba.jpg/960px-Kolumba.jpg",
    "imageFile": "Kolumba.jpg",
    "imageCredit": "Elke Wetzig ( Elya )",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Kolumba.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kolumba.jpg",
    "wikipediaPageId": 30407121,
    "wikipediaRevisionId": 1344457798,
    "wikidataId": "Q1621165",
    "wikidata": "https://www.wikidata.org/wiki/Q1621165",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Kolumba",
      "https://www.wikidata.org/wiki/Q1621165",
      "https://www.kolumba.de/"
    ]
  },
  {
    "id": "langen-foundation",
    "name": "Langen Foundation",
    "city": "Neuss",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.152383,
    "lng": 6.64461,
    "category": "architecture",
    "outdoor": false,
    "description": "Tadao Ando’s concrete-and-glass art space occupies a former NATO missile station near Neuss.",
    "whyVisit": "Minimalist architecture and reflecting water transform a military landscape into a place for looking slowly.",
    "durationMinutes": 90,
    "wikipedia": "https://de.wikipedia.org/wiki/Langen_Foundation",
    "website": "https://langenfoundation.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Neuss_%28DE%29%2C_Raketenstation_Hombroich%2C_Langen_Foundation_--_2014_--_7404.jpg/960px-Neuss_%28DE%29%2C_Raketenstation_Hombroich%2C_Langen_Foundation_--_2014_--_7404.jpg",
    "imageFile": "Neuss (DE), Raketenstation Hombroich, Langen Foundation -- 2014 -- 7404.jpg",
    "imageCredit": "Anil Öztas / Stadt Neuss",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Neuss_(DE),_Raketenstation_Hombroich,_Langen_Foundation_--_2014_--_7404.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Neuss_%28DE%29%2C_Raketenstation_Hombroich%2C_Langen_Foundation_--_2014_--_7404.jpg",
    "wikipediaPageId": 3416748,
    "wikipediaRevisionId": 261510055,
    "wikidataId": "Q830675",
    "wikidata": "https://www.wikidata.org/wiki/Q830675",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Langen_Foundation",
      "https://www.wikidata.org/wiki/Q830675",
      "https://langenfoundation.de/"
    ]
  },
  {
    "id": "insel-hombroich",
    "name": "Museum Insel Hombroich",
    "city": "Neuss",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.147412,
    "lng": 6.658745,
    "category": "museums",
    "outdoor": true,
    "description": "Freestanding art pavilions are scattered through restored parkland and river meadows beside the Erft.",
    "whyVisit": "Wander between landscape, sculpture and galleries rather than following a conventional museum route.",
    "durationMinutes": 180,
    "wikipedia": "https://de.wikipedia.org/wiki/Museum_Insel_Hombroich",
    "website": "https://www.inselhombroich.de/de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Auenlandschaft_Museumsinsel_Hombroich_Neuss_2006.jpg/960px-Auenlandschaft_Museumsinsel_Hombroich_Neuss_2006.jpg",
    "imageFile": "Auenlandschaft Museumsinsel Hombroich Neuss 2006.jpg",
    "imageCredit": "Perlblau",
    "imageLicense": "CC BY-SA 2.0 de",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Auenlandschaft_Museumsinsel_Hombroich_Neuss_2006.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/de/deed.en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/2/26/Auenlandschaft_Museumsinsel_Hombroich_Neuss_2006.jpg",
    "wikipediaPageId": 1131847,
    "wikipediaRevisionId": 265696031,
    "wikidataId": "Q10862311",
    "wikidata": "https://www.wikidata.org/wiki/Q10862311",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Museum_Insel_Hombroich",
      "https://www.wikidata.org/wiki/Q10862311",
      "https://www.inselhombroich.de/de/"
    ]
  },
  {
    "id": "muengsten-bridge",
    "name": "Müngsten Bridge",
    "city": "Solingen",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.16055556,
    "lng": 7.13333333,
    "category": "industrial",
    "outdoor": true,
    "description": "Germany’s highest railway bridge carries a great steel arch 107 metres above the wooded Wupper valley.",
    "whyVisit": "Explore the valley park below for a striking view of engineering against the forest canopy.",
    "durationMinutes": 90,
    "wikipedia": "https://en.wikipedia.org/wiki/M%C3%BCngsten_Bridge",
    "website": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Muengstener_Bruecke.jpg/960px-Muengstener_Bruecke.jpg",
    "imageFile": "Muengstener Bruecke.jpg",
    "imageCredit": "Stefan Kemmerling ( Kemmi.1 )",
    "imageLicense": "CC BY-SA 3.0 de",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Muengstener_Bruecke.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Muengstener_Bruecke.jpg",
    "wikipediaPageId": 12677123,
    "wikipediaRevisionId": 1271297591,
    "wikidataId": "Q257027",
    "wikidata": "https://www.wikidata.org/wiki/Q257027",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/M%C3%BCngsten_Bridge",
      "https://www.wikidata.org/wiki/Q257027"
    ]
  },
  {
    "id": "wuppertal-schwebebahn",
    "name": "Wuppertal Suspension Railway",
    "city": "Wuppertal",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.26708889,
    "lng": 7.181425,
    "category": "industrial",
    "outdoor": true,
    "description": "Trains hang beneath an elevated rail that threads along the Wupper, a remarkable transport system opened in 1901.",
    "whyVisit": "See a working city from an improbable angle; this is real public transport, not a theme-park ride.",
    "durationMinutes": 90,
    "wikipedia": "https://de.wikipedia.org/wiki/Wuppertaler_Schwebebahn",
    "website": "https://schwebebahn.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Schwebebahn_G15.jpg/960px-Schwebebahn_G15.jpg",
    "imageFile": "Schwebebahn G15.jpg",
    "imageCredit": "Max Grobecker",
    "imageLicense": "CC BY-SA 2.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Schwebebahn_G15.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/3/30/Schwebebahn_G15.jpg",
    "wikipediaPageId": 4576,
    "wikipediaRevisionId": 271107342,
    "wikidataId": "Q256964",
    "wikidata": "https://www.wikidata.org/wiki/Q256964",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Wuppertaler_Schwebebahn",
      "https://www.wikidata.org/wiki/Q256964",
      "https://schwebebahn.de/"
    ]
  },
  {
    "id": "tiger-and-turtle",
    "name": "Tiger & Turtle — Magic Mountain",
    "city": "Duisburg",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.375558,
    "lng": 6.738031,
    "category": "architecture",
    "outdoor": true,
    "description": "A walkable steel sculpture curls like a roller coaster above a former industrial landscape in Duisburg.",
    "whyVisit": "Climb the stairways for Ruhr views and impossible-looking photographs; the vertical loop itself is closed to walkers.",
    "durationMinutes": 60,
    "wikipedia": "https://de.wikipedia.org/wiki/Tiger_and_Turtle_%E2%80%93_Magic_Mountain",
    "website": "https://www.duisburg.de/tourismus/stadt_erleben/industriekultur/tiger-and-turtle",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Duisburg_-_Angerpark_-_Tiger_and_Turtle_-_2018.jpg/960px-Duisburg_-_Angerpark_-_Tiger_and_Turtle_-_2018.jpg",
    "imageFile": "Duisburg - Angerpark - Tiger and Turtle - 2018.jpg",
    "imageCredit": "Avda",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Duisburg_-_Angerpark_-_Tiger_and_Turtle_-_2018.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Duisburg_-_Angerpark_-_Tiger_and_Turtle_-_2018.jpg",
    "wikipediaPageId": 6592276,
    "wikipediaRevisionId": 260299023,
    "wikidataId": "Q1800283",
    "wikidata": "https://www.wikidata.org/wiki/Q1800283",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Tiger_and_Turtle_%E2%80%93_Magic_Mountain",
      "https://www.wikidata.org/wiki/Q1800283",
      "https://www.duisburg.de/tourismus/stadt_erleben/industriekultur/tiger-and-turtle"
    ]
  },
  {
    "id": "tetrahedron",
    "name": "Tetrahedron",
    "city": "Bottrop",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.527,
    "lng": 6.96,
    "category": "architecture",
    "outdoor": true,
    "description": "A giant open steel tetrahedron balances on concrete pillars atop the Halde Beckstraße mine spoil heap.",
    "whyVisit": "The uphill walk ends with geometric drama, suspended stairs and far-reaching views over the Ruhr.",
    "durationMinutes": 90,
    "wikipedia": "https://en.wikipedia.org/wiki/Tetrahedron_in_Bottrop",
    "website": "https://www.bottrop.de/freizeit-tourismus/sehenswert/Tetraeder.php",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Bottrop_%28DE%29%2C_Tetraeder_--_2022_--_0402.jpg/960px-Bottrop_%28DE%29%2C_Tetraeder_--_2022_--_0402.jpg",
    "imageFile": "Bottrop (DE), Tetraeder -- 2022 -- 0402.jpg",
    "imageCredit": "© Anil Öztas",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Bottrop_(DE),_Tetraeder_--_2022_--_0402.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Bottrop_%28DE%29%2C_Tetraeder_--_2022_--_0402.jpg",
    "wikipediaPageId": 39828586,
    "wikipediaRevisionId": 1345248860,
    "wikidataId": "Q896623",
    "wikidata": "https://www.wikidata.org/wiki/Q896623",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Tetrahedron_in_Bottrop",
      "https://www.wikidata.org/wiki/Q896623",
      "https://www.bottrop.de/freizeit-tourismus/sehenswert/Tetraeder.php"
    ]
  },
  {
    "id": "landschaftspark",
    "name": "Landschaftspark Duisburg-Nord",
    "city": "Duisburg",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.48027778,
    "lng": 6.78,
    "category": "industrial",
    "outdoor": true,
    "description": "Blast furnaces, pipes and ore bunkers form a public park on the grounds of a former ironworks.",
    "whyVisit": "Wander through a monumental industrial skeleton where vegetation has become part of the design.",
    "durationMinutes": 180,
    "wikipedia": "https://en.wikipedia.org/wiki/Landschaftspark_Duisburg-Nord",
    "website": "https://www.landschaftspark.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hochofen_5_at_Landschaftspark_Duisburg-Nord.jpg/960px-Hochofen_5_at_Landschaftspark_Duisburg-Nord.jpg",
    "imageFile": "Hochofen 5 at Landschaftspark Duisburg-Nord.jpg",
    "imageCredit": "Sch0p3nh4u3r",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hochofen_5_at_Landschaftspark_Duisburg-Nord.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/9/90/Hochofen_5_at_Landschaftspark_Duisburg-Nord.jpg",
    "wikipediaPageId": 5121474,
    "wikipediaRevisionId": 1379156688,
    "wikidataId": "Q523126",
    "wikidata": "https://www.wikidata.org/wiki/Q523126",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Landschaftspark_Duisburg-Nord",
      "https://www.wikidata.org/wiki/Q523126",
      "https://www.landschaftspark.de/"
    ]
  },
  {
    "id": "zollverein",
    "name": "Zollverein Coal Mine",
    "city": "Essen",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.49138889,
    "lng": 7.04611111,
    "category": "industrial",
    "outdoor": true,
    "description": "A UNESCO-listed coal mine and coking plant combine red-brick industrial buildings with monumental steel machinery.",
    "whyVisit": "Follow the vast former production landscape and its strikingly disciplined architecture.",
    "durationMinutes": 180,
    "wikipedia": "https://en.wikipedia.org/wiki/Zollverein_Coal_Mine_Industrial_Complex",
    "website": "https://www.zollverein.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Zeche_Zollverein_abends.jpg/960px-Zeche_Zollverein_abends.jpg",
    "imageFile": "Zeche Zollverein abends.jpg",
    "imageCredit": "Thomas Wolf, www.foto-tw.de",
    "imageLicense": "CC BY-SA 3.0 de",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Zeche_Zollverein_abends.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/4/43/Zeche_Zollverein_abends.jpg",
    "wikipediaPageId": 13257595,
    "wikipediaRevisionId": 1378534011,
    "wikidataId": "Q122026",
    "wikidata": "https://www.wikidata.org/wiki/Q122026",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Zollverein_Coal_Mine_Industrial_Complex",
      "https://www.wikidata.org/wiki/Q122026",
      "https://www.zollverein.de/"
    ]
  },
  {
    "id": "gasometer",
    "name": "Gasometer Oberhausen",
    "city": "Oberhausen",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.494167,
    "lng": 6.870556,
    "category": "industrial",
    "outdoor": false,
    "description": "A towering former gas holder has been reinvented as a venue for large-scale exhibitions.",
    "whyVisit": "Experience art and ideas inside one of the Ruhr’s most unusual industrial interiors.",
    "durationMinutes": 120,
    "wikipedia": "https://en.wikipedia.org/wiki/Gasometer_Oberhausen",
    "website": "https://www.gasometer.de/de",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Germany_gasometer_oberhausen_neue_mitte.jpg/960px-Germany_gasometer_oberhausen_neue_mitte.jpg",
    "imageFile": "Germany gasometer oberhausen neue mitte.jpg",
    "imageCredit": "Arne Müseler",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Germany_gasometer_oberhausen_neue_mitte.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Germany_gasometer_oberhausen_neue_mitte.jpg",
    "wikipediaPageId": 21875097,
    "wikipediaRevisionId": 1345196639,
    "wikidataId": "Q515921",
    "wikidata": "https://www.wikidata.org/wiki/Q515921",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Gasometer_Oberhausen",
      "https://www.wikidata.org/wiki/Q515921",
      "https://www.gasometer.de/de"
    ]
  },
  {
    "id": "henrichenburg-boat-lift",
    "name": "Henrichenburg Boat Lift",
    "city": "Waltrop",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.61658,
    "lng": 7.32587,
    "category": "industrial",
    "outdoor": true,
    "description": "An elaborate 1899 ship lift once raised boats between canal levels; today the preserved structure anchors an industrial museum.",
    "whyVisit": "Discover the ingenious machinery that made entire vessels travel vertically.",
    "durationMinutes": 120,
    "wikipedia": "https://de.wikipedia.org/wiki/Schiffshebewerk_Henrichenburg",
    "website": "https://schiffshebewerk-henrichenburg.lwl.org/de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Altes-Hebewerk-Henrichenburg-2023.jpg/960px-Altes-Hebewerk-Henrichenburg-2023.jpg",
    "imageFile": "Altes-Hebewerk-Henrichenburg-2023.jpg",
    "imageCredit": "Awistreich",
    "imageLicense": "CC BY 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Altes-Hebewerk-Henrichenburg-2023.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/2/26/Altes-Hebewerk-Henrichenburg-2023.jpg",
    "wikipediaPageId": 195338,
    "wikipediaRevisionId": 269691905,
    "wikidataId": "Q99406",
    "wikidata": "https://www.wikidata.org/wiki/Q99406",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Schiffshebewerk_Henrichenburg",
      "https://www.wikidata.org/wiki/Q99406",
      "https://schiffshebewerk-henrichenburg.lwl.org/de/"
    ]
  },
  {
    "id": "externsteine",
    "name": "Externsteine",
    "city": "Horn-Bad Meinberg",
    "region": "North Rhine-Westphalia",
    "country": "Germany",
    "lat": 51.869,
    "lng": 8.9173,
    "category": "nature",
    "outdoor": true,
    "description": "Tall sandstone pillars rise abruptly beside a pond and woodland in the Teutoburg Forest.",
    "whyVisit": "Explore a dramatic rock landscape with medieval carvings and centuries of stories, without mistaking legend for proven history.",
    "durationMinutes": 120,
    "wikipedia": "https://en.wikipedia.org/wiki/Externsteine",
    "website": "https://www.externsteine-info.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Externsteine_High_Resolution_v2_2015.jpg/960px-Externsteine_High_Resolution_v2_2015.jpg",
    "imageFile": "Externsteine High Resolution v2 2015.jpg",
    "imageCredit": "Tuxyso / Wikimedia Commons",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Externsteine_High_Resolution_v2_2015.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Externsteine_High_Resolution_v2_2015.jpg",
    "wikipediaPageId": 345904,
    "wikipediaRevisionId": 1369855360,
    "wikidataId": "Q319172",
    "wikidata": "https://www.wikidata.org/wiki/Q319172",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/Externsteine",
      "https://www.wikidata.org/wiki/Q319172",
      "https://www.externsteine-info.de/"
    ]
  },
  {
    "id": "rakotzbruecke",
    "name": "Rakotzbrücke",
    "city": "Gablenz",
    "region": "Saxony",
    "country": "Germany",
    "lat": 51.536302,
    "lng": 14.640477,
    "category": "architecture",
    "outdoor": true,
    "description": "A steep stone arch in Kromlau’s landscaped park forms an almost perfect circle when reflected in the water below.",
    "whyVisit": "Find the famous reflection from the lakeside paths; this is a protected monument to admire, not a bridge to cross.",
    "durationMinutes": 90,
    "wikipedia": "https://de.wikipedia.org/wiki/Rakotzbr%C3%BCcke",
    "website": "https://kromlau-online.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Rakotzbr%C3%BCcke.jpg/960px-Rakotzbr%C3%BCcke.jpg",
    "imageFile": "Rakotzbrücke.jpg",
    "imageCredit": "A.Landgraf",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg",
    "wikipediaPageId": 12007351,
    "wikipediaRevisionId": 269563584,
    "wikidataId": "Q49418029",
    "wikidata": "https://www.wikidata.org/wiki/Q49418029",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Rakotzbr%C3%BCcke",
      "https://www.wikidata.org/wiki/Q49418029",
      "https://kromlau-online.de/"
    ]
  },
  {
    "id": "voelklingen-ironworks",
    "name": "Völklingen Ironworks",
    "city": "Völklingen",
    "region": "Saarland",
    "country": "Germany",
    "lat": 49.24444444,
    "lng": 6.85,
    "category": "industrial",
    "outdoor": true,
    "description": "A preserved blast-furnace complex turns the machinery of iron production into a UNESCO-listed industrial landscape.",
    "whyVisit": "Explore the immense layers of pipes, furnaces and steelwork at one of Germany’s defining industrial monuments.",
    "durationMinutes": 180,
    "wikipedia": "https://en.wikipedia.org/wiki/V%C3%B6lklingen_Ironworks",
    "website": "https://voelklinger-huette.org/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/VH_pano5_1.jpg/960px-VH_pano5_1.jpg",
    "imageFile": "VH pano5 1.jpg",
    "imageCredit": "Lokilech",
    "imageLicense": "CC BY-SA 3.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:VH_pano5_1.jpg",
    "imageLicenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/d/d0/VH_pano5_1.jpg",
    "wikipediaPageId": 6809871,
    "wikipediaRevisionId": 1376375338,
    "wikidataId": "Q127754",
    "wikidata": "https://www.wikidata.org/wiki/Q127754",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://en.wikipedia.org/wiki/V%C3%B6lklingen_Ironworks",
      "https://www.wikidata.org/wiki/Q127754",
      "https://voelklinger-huette.org/"
    ]
  },
  {
    "id": "beelitz-treetop-walk",
    "name": "Beelitz-Heilstätten Treetop Walk",
    "city": "Beelitz",
    "region": "Brandenburg",
    "country": "Germany",
    "lat": 52.26369444,
    "lng": 12.91913889,
    "category": "architecture",
    "outdoor": true,
    "description": "An elevated walkway crosses the woodland and former tuberculosis-sanatorium grounds at Beelitz-Heilstätten.",
    "whyVisit": "See historic hospital architecture from the treetops through the managed Baum & Zeit visitor site, not by entering unsafe ruins.",
    "durationMinutes": 150,
    "wikipedia": "https://de.wikipedia.org/wiki/Baumkronenpfad_Beelitz-Heilst%C3%A4tten",
    "website": "https://baumundzeit.de/",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Baumkronenpfad_Beelitz_Heilst%C3%A4tten.JPG/960px-Baumkronenpfad_Beelitz_Heilst%C3%A4tten.JPG",
    "imageFile": "Baumkronenpfad Beelitz Heilstätten.JPG",
    "imageCredit": "Havelbaude",
    "imageLicense": "CC BY-SA 4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Baumkronenpfad_Beelitz_Heilst%C3%A4tten.JPG",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageOriginal": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Baumkronenpfad_Beelitz_Heilst%C3%A4tten.JPG",
    "wikipediaPageId": 10655571,
    "wikipediaRevisionId": 270448861,
    "wikidataId": "Q60668021",
    "wikidata": "https://www.wikidata.org/wiki/Q60668021",
    "sourceCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageMetadataCheckedAt": "2026-10-08T20:51:44.314Z",
    "imageCheckStatus": "metadata-verified",
    "sources": [
      "https://de.wikipedia.org/wiki/Baumkronenpfad_Beelitz-Heilst%C3%A4tten",
      "https://www.wikidata.org/wiki/Q60668021",
      "https://baumundzeit.de/"
    ]
  }
];

export const cities = {
  "Bonn": {
    "lat": 50.7374,
    "lng": 7.0982
  },
  "Cologne": {
    "lat": 50.9375,
    "lng": 6.9603
  },
  "Düsseldorf": {
    "lat": 51.2277,
    "lng": 6.7735
  },
  "Duisburg": {
    "lat": 51.4344,
    "lng": 6.7623
  },
  "Essen": {
    "lat": 51.4556,
    "lng": 7.0116
  },
  "Dortmund": {
    "lat": 51.5136,
    "lng": 7.4653
  },
  "Wuppertal": {
    "lat": 51.2562,
    "lng": 7.1508
  },
  "Berlin": {
    "lat": 52.52,
    "lng": 13.405
  },
  "Hamburg": {
    "lat": 53.5511,
    "lng": 9.9937
  },
  "Munich": {
    "lat": 48.1351,
    "lng": 11.582
  },
  "Frankfurt": {
    "lat": 50.1109,
    "lng": 8.6821
  },
  "Dresden": {
    "lat": 51.0504,
    "lng": 13.7373
  },
  "Leipzig": {
    "lat": 51.3397,
    "lng": 12.3731
  },
  "Stuttgart": {
    "lat": 48.7758,
    "lng": 9.1829
  },
  "Königswinter": {
    "lat": 50.6739,
    "lng": 7.1932
  },
  "Brühl": {
    "lat": 50.8292,
    "lng": 6.9045
  },
  "Neuss": {
    "lat": 51.2042,
    "lng": 6.6879
  },
  "Mechernich": {
    "lat": 50.5906,
    "lng": 6.6528
  },
  "Bad Neuenahr-Ahrweiler": {
    "lat": 50.5444,
    "lng": 7.1197
  },
  "Remagen": {
    "lat": 50.5796,
    "lng": 7.2279
  },
  "Bad Münstereifel": {
    "lat": 50.556,
    "lng": 6.7635
  },
  "Andernach": {
    "lat": 50.4261,
    "lng": 7.4087
  },
  "Solingen": {
    "lat": 51.1652,
    "lng": 7.0671
  },
  "Bottrop": {
    "lat": 51.5291,
    "lng": 6.9447
  },
  "Oberhausen": {
    "lat": 51.4963,
    "lng": 6.8638
  },
  "Waltrop": {
    "lat": 51.6213,
    "lng": 7.3964
  },
  "Horn-Bad Meinberg": {
    "lat": 51.8856,
    "lng": 8.9778
  },
  "Gablenz": {
    "lat": 51.5343,
    "lng": 14.6703
  },
  "Völklingen": {
    "lat": 49.2516,
    "lng": 6.8587
  },
  "Beelitz": {
    "lat": 52.2381,
    "lng": 12.9714
  }
};
