export const client = String.raw`(() => {
const app = document.getElementById('app');
const zone = 'Europe/Berlin';
const state = { data:null, view:'calendar', selected:dayKey(Date.now()), month:dayKey(Date.now()).slice(0,7), friend:null, modal:null, authMode:'login' };
const icons = {
 calendar:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M7 2v4M17 2v4M3 10h18"/>',
 friends:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
 inbox:'<path d="M4 4h16v12h-4l-2 3h-4l-2-3H4z"/><path d="M8 11h8"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'
};
function svg(key){ return '<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[key]+'</svg>'; }
function esc(s){ return String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function parts(t){ const p = new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(t); return Object.fromEntries(p.map(x=>[x.type,x.value])); }
function dayKey(t){ const p=parts(t); return p.year+'-'+p.month+'-'+p.day; }
function wallTime(value){ const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value); if(!match)return null; const [y,m,d,h,min]=match.slice(1).map(Number); const base=Date.UTC(y,m-1,d,h,min); for(const hours of [2,1]){ const t=base-hours*3600000,p=parts(t); if(+p.year===y && +p.month===m && +p.day===d && +p.hour===h && +p.minute===min)return t; } return null; }
function inputTime(t){ const p=parts(t);return p.year+'-'+p.month+'-'+p.day+'T'+p.hour+':'+p.minute; }
function fmt(t, options){return new Intl.DateTimeFormat('en-GB',Object.assign({timeZone:zone},options)).format(t);}
function time(t){return fmt(t,{hour:'2-digit',minute:'2-digit'});}
function span(a,b){return time(a)+' – '+time(b);}
function longDay(date){return fmt(wallTime(date+'T12:00'),{weekday:'long',day:'numeric',month:'long'});}
function dayBounds(date){const next=new Date(Date.parse(date+'T12:00:00Z')+86400000).toISOString().slice(0,10);return [wallTime(date+'T00:00'),wallTime(next+'T00:00')];}
function onDay(item,date){const [a,b]=dayBounds(date);return item.start_at<b&&item.end_at>a;}
function initials(name){return esc(String(name).split(' ').map(x=>x[0]).slice(0,2).join(''));}
function toast(message,error){ const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),4500); }
async function api(path,method='GET',body){const opts={method,headers:body?{'Content-Type':'application/json'}:{}};if(body)opts.body=JSON.stringify(body);let r=await fetch('/api/'+path,opts),out=await r.json();if(!r.ok)throw Error(out.error||'Something went wrong.');return out;}
async function load(){try{state.data=await api('bootstrap');if(state.friend && !state.data.friends.find(f=>f.id===state.friend))state.friend=null;render();}catch(e){if(e.message==='Please sign in.'){state.data=null;render();}else toast(e.message,true);}}
async function action(path,body,method='POST',message){try{await api(path,method,body);if(message)toast(message);await load();}catch(e){toast(e.message,true);}}
const own=()=>state.data.slots.filter(s=>s.user_id===state.data.user.id);
const friend=()=>state.data.friends.find(f=>f.id===state.friend);
const friendSlots=()=>state.friend?state.data.slots.filter(s=>s.user_id===state.friend):[];
const incoming=()=>state.data.friendships.filter(f=>f.status==='pending'&&f.addressee_id===state.data.user.id);
const pendingMeetings=()=>state.data.meetings.filter(m=>m.status==='pending'&&m.recipient_id===state.data.user.id);
function shell(){const u=state.data.user,n=incoming().length+pendingMeetings().length;return '<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">✳</span> daybreak</div><div class="side-label">YOUR SPACE</div><nav class="nav">'+[['calendar','Calendar','calendar'],['friends','Friends','friends'],['requests','Requests','inbox'],['meetings','Meetings','clock']].map(([v,label,icon])=>'<button data-view="'+v+'" class="'+(state.view===v?'active':'')+'">'+svg(icon)+label+(v==='requests'&&n?'<span class="badge">'+n+'</span>':'')+'</button>').join('')+'</nav><div class="sidebar-bottom"><div class="profile"><span class="avatar">'+initials(u.name)+'</span><div><strong>'+esc(u.name)+'</strong><small>'+esc(u.email)+'</small></div></div><button class="logout" data-action="logout">↪ &nbsp; Log out</button></div></aside><main class="main"><div class="content"><div class="topline"><div class="crumb">Your space &nbsp;/&nbsp; <span>'+({calendar:'Calendar',friends:'Friends',requests:'Requests',meetings:'Meetings'}[state.view])+'</span></div><div class="timezone"><i></i> CET / CEST · Berlin time</div></div>'+({calendar:calendarView,friends:friendsView,requests:requestsView,meetings:meetingsView}[state.view])()+'</div></main></div>'+(state.modal?modal():'');}
function hero(label,title,sub,button){return '<div class="hero"><div><div class="eyebrow">'+label+'</div><h1>'+title+'</h1><p>'+sub+'</p></div>'+button+'</div>';}
function calendarView(){return hero('A LITTLE MORE TIME TOGETHER','Make room for good company.','Your free time, all in one place. Pick a day to see what’s happening.','<button class="btn primary" data-action="add-slot">＋ &nbsp; Add free time</button>')+'<div class="layout"><section class="panel calendar">'+calendarGrid()+'</section><div class="right-stack"><section class="panel card-pad">'+dayPanel()+'</section><section class="panel card-pad">'+friendPanel()+'</section></div></div><section class="panel card-pad below">'+meetingPreview()+'</section>';}
function calendarGrid(){let [y,m]=state.month.split('-').map(Number),first=(new Date(Date.UTC(y,m-1,1)).getUTCDay()+6)%7,count=new Date(Date.UTC(y,m,0)).getUTCDate(),prev=new Date(Date.UTC(y,m-1,0)).getUTCDate(),cells='';const slots=[...own(),...friendSlots()];const booked=state.data.meetings.filter(x=>x.status==='accepted');for(let i=0;i<42;i++){let n=i-first+1,dt=new Date(Date.UTC(y,m-1,n)),key=dt.toISOString().slice(0,10),dim=n<1||n>count;let dots='';if(slots.some(s=>s.user_id===state.data.user.id&&onDay(s,key)))dots+='<i class="dot"></i>';if(slots.some(s=>s.user_id===state.friend&&onDay(s,key)))dots+='<i class="dot friend"></i>';if(booked.some(b=>onDay(b,key)))dots+='<i class="dot booked"></i>';cells+='<button class="day'+(dim?' muted':'')+(key===dayKey(Date.now())?' today':'')+(key===state.selected?' selected':'')+'" data-day="'+key+'" aria-label="'+key+'"><span class="number">'+dt.getUTCDate()+'</span><span class="dots">'+dots+'</span></button>';}
return '<div class="panel-head"><div><h2>Calendar</h2><p>A clearer view of your days</p></div><div class="cal-actions"><button data-month="-1" aria-label="Previous month">‹</button><span class="month">'+fmt(wallTime(state.month+'-01T12:00'),{month:'long',year:'numeric'})+'</span><button data-month="1" aria-label="Next month">›</button></div></div><div class="weekdays">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>'<span>'+x+'</span>').join('')+'</div><div class="days">'+cells+'</div><div class="legend"><span><i class="dot"></i>Your free time</span><span><i class="dot friend"></i>Friend’s free time</span><span><i class="dot booked"></i>Booked</span></div>';}
function dayPanel(){const ownToday=own().filter(s=>onDay(s,state.selected)),friendToday=friendSlots().filter(s=>onDay(s,state.selected)),meetings=state.data.meetings.filter(m=>m.status==='accepted'&&onDay(m,state.selected));let items=[...ownToday.map(s=>({kind:'own',s})),...friendToday.map(s=>({kind:'friend',s})),...meetings.map(s=>({kind:'booked',s}))].sort((a,b)=>a.s.start_at-b.s.start_at);return '<div class="mini-label">SELECTED DAY</div><h2 class="date-title">'+longDay(state.selected)+'</h2><div class="slot-list">'+(items.length?items.map(({kind,s})=>'<div class="slot"><span class="slot-mark '+kind+'"></span><div class="slot-info"><strong>'+span(s.start_at,s.end_at)+'</strong><small>'+(kind==='own'?'Your free time':kind==='friend'?esc(friend().name)+' is free':'Booked · '+esc(s.requester_id===state.data.user.id?s.recipient_name:s.requester_name))+'</small></div>'+(kind==='own'?'<button class="iconbtn" data-delete-slot="'+s.id+'" title="Remove free time" aria-label="Remove free time">×</button>':'')+'</div>').join(''):'<div class="empty">Nothing on the calendar for this day.<br>Good days start with a little free time.</div>')+'</div>'+(friend()&&friendToday.length?'<h3 class="section-heading">Time together</h3>'+sharedForDay(friendToday):'');}
function sharedForDay(slots){let shared=[];const [dayStart,dayEnd]=dayBounds(state.selected);for(const f of slots)for(const o of own()){let a=Math.max(f.start_at,o.start_at,dayStart),b=Math.min(f.end_at,o.end_at,dayEnd);if(a<b&&a>Date.now())shared.push({a,b});}return shared.length?shared.map(x=>'<div class="shared-window"><div><strong>'+span(x.a,x.b)+'</strong><small>Both of you are free</small></div><button class="btn primary small" data-book="'+x.a+','+x.b+'">Request</button></div>').join(''):'<div class="empty">No shared free time on this day yet.</div>';}
function friendPanel(){return '<div class="split-header"><h2>Friends</h2><button class="textbtn" data-view="friends">View all →</button></div>'+(state.data.friends.length?state.data.friends.map(f=>'<div class="friend-row'+(state.friend===f.id?' selected':'')+'"><span class="avatar">'+initials(f.name)+'</span><div class="info"><strong>'+esc(f.name)+'</strong><small>'+esc(f.email)+'</small></div><button data-friend="'+f.id+'">'+(state.friend===f.id?'Viewing':'View slots')+'</button></div>').join(''):'<div class="empty">It’s better together.<br>Add a friend by email to share availability.</div>')+(friend()?'<p class="muted" style="margin-top:12px">Showing '+esc(friend().name)+'’s free slots in your calendar. Select a day to see them all.</p>':'');}
function meetingPreview(){let m=state.data.meetings.filter(x=>x.status==='accepted'&&x.end_at>Date.now()).slice(0,3);return '<div class="split-header"><h2>Coming up</h2><button class="textbtn" data-view="meetings">All meetings →</button></div>'+(m.length?m.map(meetingRow).join(''):'<div class="empty">No plans yet. A free afternoon could change that.</div>');}
function meetingRow(m){let other=m.requester_id===state.data.user.id?m.recipient_name:m.requester_name;return '<div class="meeting-row"><span class="meeting-icon">✳</span><div class="info"><strong>Time with '+esc(other)+'</strong><small>'+fmt(m.start_at,{weekday:'short',day:'numeric',month:'short'})+' · '+span(m.start_at,m.end_at)+'</small></div><span class="pill '+(m.status==='pending'?'pending':'')+'">'+esc(m.status)+'</span></div>';}
function friendsView(){return hero('YOUR PEOPLE','Better together.','Add friends by their registered email address. Once they accept, you can see all their free time.','')+'<div class="two-col"><section class="panel fullpanel"><h2 style="font-size:18px">Add a friend</h2><p class="muted" style="margin-top:7px">Send a request to someone already on Daybreak.</p><form id="friend-form" class="form-inline"><input class="input" type="email" name="email" placeholder="friend@example.com" required aria-label="Friend’s email"><button class="btn primary">Send request</button></form><h3 class="section-heading">Your friends · '+state.data.friends.length+'</h3>'+(state.data.friends.length?state.data.friends.map(f=>'<div class="friend-row"><span class="avatar">'+initials(f.name)+'</span><div class="info"><strong>'+esc(f.name)+'</strong><small>'+esc(f.email)+'</small></div><button data-friend="'+f.id+'">View calendar</button></div>').join(''):'<div class="empty">No friends yet. Send the first request!</div>')+'</section><section class="panel fullpanel"><h2 style="font-size:18px">Friend requests</h2><h3 class="section-heading">Received</h3>'+(incoming().length?incoming().map(f=>requestCard(f,'received')).join(''):'<p class="muted">No incoming requests.</p>')+'<h3 class="section-heading">Sent</h3>'+(state.data.friendships.filter(f=>f.status==='pending'&&f.requester_id===state.data.user.id).map(f=>requestCard(f,'sent')).join('')||'<p class="muted">No pending requests.</p>')+'</section></div>';}
function requestCard(f,kind){return '<div class="request-card"><div><strong>'+esc(kind==='received'?f.requester_name:f.addressee_name)+'</strong><small>'+esc(kind==='received'?f.requester_email:f.addressee_email)+'</small></div><div class="actions">'+(kind==='received'?'<button class="btn primary small" data-friend-response="'+f.id+',accept">Accept</button><button class="btn ghost small" data-friend-response="'+f.id+',decline">Decline</button>':'<button class="btn ghost small" data-friend-response="'+f.id+',cancel">Cancel</button>')+'</div></div>';}
function requestsView(){let received=pendingMeetings(),sent=state.data.meetings.filter(m=>m.status==='pending'&&m.requester_id===state.data.user.id);return hero('IN YOUR INBOX','A little invitation.','Accept an invitation to reserve that time for both of you.','')+'<section class="panel fullpanel"><h2 style="font-size:18px">Meeting requests</h2><h3 class="section-heading">Received · '+received.length+'</h3>'+(received.length?received.map(m=>meetingRequest(m,'received')).join(''):'<div class="empty">No incoming invitations right now.</div>')+'<h3 class="section-heading">Sent · '+sent.length+'</h3>'+(sent.length?sent.map(m=>meetingRequest(m,'sent')).join(''):'<p class="muted">No outgoing requests.</p>')+'</section><section class="panel fullpanel"><h2 style="font-size:18px">Friend requests</h2>'+(incoming().length?incoming().map(f=>requestCard(f,'received')).join(''):'<p class="muted" style="margin-top:12px">All caught up.</p>')+'</section>';}
function meetingRequest(m,kind){return '<div class="request-card"><div><strong>'+esc(kind==='received'?m.requester_name:m.recipient_name)+'</strong><small>'+fmt(m.start_at,{weekday:'short',day:'numeric',month:'short'})+' · '+span(m.start_at,m.end_at)+'</small></div><div class="actions">'+(kind==='received'?'<button class="btn primary small" data-meeting-response="'+m.id+',accept">Accept</button><button class="btn ghost small" data-meeting-response="'+m.id+',decline">Decline</button>':'<button class="btn ghost small" data-meeting-response="'+m.id+',cancel">Cancel</button>')+'</div></div>';}
function meetingsView(){let booked=state.data.meetings.filter(m=>m.status==='accepted'&&m.end_at>Date.now()),past=state.data.meetings.filter(m=>m.status==='accepted'&&m.end_at<=Date.now());return hero('PLANS WORTH MAKING','Time well spent.','Accepted plans are reserved for both of you. All times are shown in CET / CEST.','')+'<section class="panel fullpanel"><h2 style="font-size:18px">Upcoming · '+booked.length+'</h2>'+(booked.length?booked.map(meetingRow).join(''):'<div class="empty">No upcoming meetings yet.</div>')+'</section>'+(past.length?'<section class="panel fullpanel"><h2 style="font-size:18px">Past meetings</h2>'+past.map(meetingRow).join('')+'</section>':'');}
function modal(){if(state.modal.type==='slot'){let start=state.selected+'T18:00',end=state.selected+'T20:00';return '<div class="modal-backdrop" data-close="1"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">Add free time</h2><p>Let your friends know when you’re around. Times are in CET / CEST.</p><form id="slot-form"><div class="field"><label for="slot-start">From</label><input id="slot-start" class="input" type="datetime-local" name="start" value="'+start+'" required></div><div class="field"><label for="slot-end">Until</label><input id="slot-end" class="input" type="datetime-local" name="end" value="'+end+'" required></div><div class="modal-actions"><button type="button" class="btn ghost" data-action="close">Cancel</button><button class="btn primary">Add free time</button></div></form></div></div>';}
let {start,end}=state.modal;return '<div class="modal-backdrop" data-close="1"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">Make a plan</h2><p>Invite '+esc(friend().name)+' to spend some time together. They’ll need to accept before it’s booked.</p><form id="meeting-form"><div class="field"><label for="meeting-start">From</label><input id="meeting-start" class="input" type="datetime-local" name="start" min="'+inputTime(start)+'" max="'+inputTime(end)+'" value="'+inputTime(start)+'" required></div><div class="field"><label for="meeting-end">Until</label><input id="meeting-end" class="input" type="datetime-local" name="end" min="'+inputTime(start)+'" max="'+inputTime(end)+'" value="'+inputTime(end)+'" required></div><div class="modal-actions"><button type="button" class="btn ghost" data-action="close">Cancel</button><button class="btn primary">Send invitation</button></div></form></div></div>';}
function auth(){let register=state.authMode==='register';return '<div class="auth-wrap"><div class="auth-art"><div class="brand"><span class="brand-icon">✳</span> daybreak</div><div><h1>Good times start with free time.</h1><p>A simple place to share your availability, find a moment that works, and make plans with your favorite people.</p></div><span class="auth-foot">More time together, less back-and-forth. ✳</span><div class="shape"></div></div><div class="auth-side"><div class="auth-box"><div class="eyebrow">WELCOME TO DAYBREAK</div><h2>'+(register?'Make yourself at home.':'Welcome back.')+'</h2><p>'+(register?'Create an account and start making time for the people who matter.':'Sign in to see your people, your plans, and your free time.')+'</p><form id="auth-form">'+(register?'<div class="field"><label for="auth-name">Your name</label><input id="auth-name" class="input" name="name" autocomplete="name" placeholder="Alex Morgan" minlength="2" maxlength="60" required></div>':'')+'<div class="field"><label for="auth-email">Email address</label><input id="auth-email" class="input" name="email" type="email" autocomplete="email" placeholder="you@example.com" required></div><div class="field"><label for="auth-password">Password</label><input id="auth-password" class="input" name="password" type="password" autocomplete="'+(register?'new-password':'current-password')+'" placeholder="'+(register?'At least 10 characters':'Enter your password')+'" '+(register?'minlength="10" ':'')+'required></div><button class="btn primary">'+(register?'Create account':'Sign in')+' →</button></form><div class="auth-switch">'+(register?'Already have an account?':'New around here?')+' <button data-auth-switch="1">'+(register?'Sign in':'Create an account')+'</button></div></div></div></div>';}
function render(){app.innerHTML=state.data?shell():auth();}
app.addEventListener('click',async e=>{const target=e.target.closest('[data-view],[data-action],[data-day],[data-month],[data-friend],[data-delete-slot],[data-book],[data-friend-response],[data-meeting-response],[data-auth-switch],[data-close]');if(!target)return;
if(target.dataset.close && e.target!==target)return;
if(target.dataset.view){state.view=target.dataset.view;render();}
else if(target.dataset.day){state.selected=target.dataset.day;state.month=state.selected.slice(0,7);render();}
else if(target.dataset.month){let [y,m]=state.month.split('-').map(Number),d=new Date(Date.UTC(y,m-1+Number(target.dataset.month),1));state.month=d.toISOString().slice(0,7);render();}
else if(target.dataset.friend){state.friend=target.dataset.friend;state.view='calendar';render();}
else if(target.dataset.authSwitch){state.authMode=state.authMode==='login'?'register':'login';render();}
else if(target.dataset.deleteSlot){if(confirm('Remove this free time?'))await action('slots/'+target.dataset.deleteSlot,null,'DELETE','Free time removed.');}
else if(target.dataset.book){let [start,end]=target.dataset.book.split(',').map(Number);state.modal={type:'meeting',start,end};render();}
else if(target.dataset.friendResponse){let [id,choice]=target.dataset.friendResponse.split(',');await action('friends/respond',{id,action:choice},'POST',choice==='accept'?'You’re friends now!':'Request updated.');}
else if(target.dataset.meetingResponse){let [id,choice]=target.dataset.meetingResponse.split(',');await action('meetings/respond',{id,action:choice},'POST',choice==='accept'?'Time together is booked!':'Request updated.');}
else if(target.dataset.action==='logout'){await action('auth/logout',{},'POST');state.data=null;state.friend=null;state.view='calendar';render();}
else if(target.dataset.action==='add-slot'){state.modal={type:'slot'};render();}
else if(target.dataset.action==='close'||target.dataset.close){state.modal=null;render();}
});
app.addEventListener('submit',async e=>{e.preventDefault();const form=e.target, data=Object.fromEntries(new FormData(form));if(form.id==='auth-form'){try{await api('auth/'+(state.authMode==='register'?'register':'login'),'POST',data);await load();}catch(err){toast(err.message,true);}}else if(form.id==='friend-form'){await action('friends/request',{email:data.email},'POST','Friend request sent!');}
else if(form.id==='slot-form'||form.id==='meeting-form'){const start=wallTime(data.start),end=wallTime(data.end);if(start===null||end===null||end<=start){toast('Choose valid start and end times in CET / CEST.',true);return;}if(form.id==='meeting-form'&&(start<state.modal.start||end>state.modal.end)){toast('Choose a time inside the shared free slot.',true);return;}const path=form.id==='slot-form'?'slots':'meetings/request',body=form.id==='slot-form'?{start,end}:{friendId:state.friend,start,end};try{await api(path,'POST',body);state.modal=null;state.selected=dayKey(start);state.month=state.selected.slice(0,7);toast(path==='slots'?'Free time added!':'Invitation sent!');await load();}catch(err){toast(err.message,true);}}
});
load();
})();`;
