// Generated by `pnpm run reset-password <email>` when an administrator needs to reset a password.
// Deploy the generated change with `pnpm run deploy`; clear this file afterwards.
export const passwordReset = null;
